name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test
      id: test
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test
        setup-command: ''
        command: javac BloodDonationEligibility.java && java BloodDonationEligibility
        input: |-
          22
          55
          22
          49
        expected-output: |-
          Enter Emma's age: Enter Emma's weight (in kg): Enter Ryan's age: Enter Ryan's weight (in kg): Emma's eligibility: Eligible
          Ryan's eligibility: Not eligible
          Ryan's eligibility after gaining 2 kg: Eligible
        comparison-method: exact
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST_RESULTS: "${{steps.test.outputs.result}}"
      with:
        runners: test
